# Generated by Django 5.0.7 on 2026-05-21 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название помещения')),
                ('capacity', models.IntegerField(default=50, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата начала')),
                ('payment', models.CharField(choices=[('cash', 'Наличными'), ('card', 'По карте'), ('transfer', 'Безналичный')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('scheduled', 'Мероприятие назначено'), ('completed', 'Мероприятие завершено')], default='new', max_length=20, verbose_name='Статус')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hall', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
